---

- gather_facts: true
  hosts: all
  tasks:
    - include_role:
        name: elasticsearch

    - include_role:
        name: kibana

    - include_role:
        name: metricbeat

    - include_role:
        name: logstash
